### ISSUE TITLE
multiple compilation errors

### ISSUE THREAD

**Issue by nick-youngblut** [koen-github/PushBullet-ESP8266#5]
I could not get the library to compile in the Arduino IDE 1.9.0-beta unless I changed the following in the `PushBullet.cpp` file:

### Change 1
removed `if(` at line54

### Change 2 
Changed 
```
sendAndToggl("/v2/pushes", "{\"body\":\""+message+"\",\"title\":\""+title+"\",\"type\":\"note\"}");
```

to
```
	String req = buildRequest("/v2/pushes", "{\"body\":\""+message+"\",\"title\":\""+title+"\",\"type\":\"note\"}");
	sendAndToggl(req);
```

for `PushBullet::sendNotePush`,  `PushBullet::sendLinkPush`, `PushBullet::sendSMSPush`, and `PushBullet::copyToClipboard`

### Notes

It appears that 124553e874bdd320962a22e462a54647a7cd4d2e introduced all of these lines which caused the compilation issues for me

**Comment by sparky3387** [comment]
Also PushBulllet.h has copyToClipboard definded as void while the cpp has it as a bool
